### ISSUE TITLE
fcli tool fod-uploader install : existing folder deleted and fod-uploader install failed IF -y is used in command

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#178] opened 2022-12-12 19:36 UTC
![image](https://user-images.githubusercontent.com/120057653/207138005-2e59a595-a28b-43e4-a2b0-7e55dbdbfb14.png)

**Comment by rsenden** [comment] 2022-12-14 13:56
Cannot reproduce with fcli v1.0.0; maybe just a temporary glitch? Can you please try again?

![image](https://user-images.githubusercontent.com/8635138/207613714-bf46743f-2835-49a4-a0ed-07ebcb3c14a4.png)

**Comment by rsenden** [comment] 2022-12-20 10:40
Closing this issue for now, as it cannot be reproduced. Please re-open if you experience the same issue again.

**Closed by rsenden** 2022-12-20 10:40 UTC
