### ISSUE TITLE
fcli ssc app update -d desc -n name --session session APP -> error if name used as parameter // MAC 

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#174] opened 2022-12-12 15:15 UTC
[debugLog.log](https://github.com/fortify-ps/fcli/files/10209446/debugLog.log)
using name as parameter throws cmd line error, the update in SSC finished successfully though

javax.validation.ValidationException: No application found for application name or id: RWI
	at com.fortify.cli.ssc.app.helper.SSCAppHelper.getApp(SSCAppHelper.java:51)
	at com.fortify.cli.ssc.app.cli.mixin.SSCAppResolverMixin$AbstractSSCAppResolverMixin.getAppDescriptor(SSCAppResolverMixin.java:44)
	at com.fortify.cli.ssc.app.cli.cmd.SSCAppUpdateCommand.getJsonNode(SSCAppUpdateCommand.java:63)
	at com.fortify.cli.common.output.cli.cmd.unirest.AbstractUnirestOutputCommand.run(AbstractUnirestOutputCommand.java:54)
	at com.fortify.cli.common.rest.cli.mixin.AbstractUnirestRunnerMixin.run(AbstractUnirestRunnerMixin.java:27)
	at com.fortify.cli.common.rest.cli.mixin.AbstractSimpleUnirestRunnerMixin.run(AbstractSimpleUnirestRunnerMixin.java:14)
	at com.fortify.cli.common.rest.cli.cmd.AbstractUnirestRunnerCommand.run(AbstractUnirestRunnerCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)

**Comment by rsenden** [comment] 2022-12-13 11:11
Duplicate of #166

**Closed by rsenden** 2022-12-13 11:11 UTC
