### ISSUE TITLE
fcli tool sc-client install -d /Users/qaprague/fcli-demo/scancentral -t 'secret!' latest

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#200] opened 2022-12-14 15:28 UTC
fcli tool sc-client install -d /Users/qaprague/fcli-demo/scancentral -t 'secret!' latest

java.lang.IllegalStateException: Digest mismatch
 Expected: 534034b322811b6eb15289c5ae538837c615f2d94ef17f24a1d5c26f492b98e0
 Actual:   44d49bddbf73703cbca619eff05c4d5aff6725b0b1809717722b63c0a3f4c9ae
	at com.fortify.cli.tool.common.cli.cmd.AbstractToolInstallCommand.checkDigest(AbstractToolInstallCommand.java:143)
	at com.fortify.cli.tool.common.cli.cmd.AbstractToolInstallCommand.downloadAndInstall(AbstractToolInstallCommand.java:76)
	at com.fortify.cli.tool.common.cli.cmd.AbstractToolInstallCommand.getJsonNode(AbstractToolInstallCommand.java:56)
	at com.fortify.cli.common.output.cli.cmd.basic.AbstractBasicOutputCommand.run(AbstractBasicOutputCommand.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)

**Comment by rsenden** [comment] 2022-12-15 10:24
Duplicate of #179, which was already fixed (but not yet released) in dac4b373571b11c81f48e9319dc889a911e22704

**Closed by rsenden** 2022-12-15 10:24 UTC
